version: '3.8'

services:
  my-app:
    container_name: my-app-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env 
    depends_on:
      - my-postgres
    networks:
      - my-network

  my-postgres:
    container_name: my-postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: dogayag1
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: assignmentkonzek
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
